### ISSUE TITLE
Свойство `overflow` относится к группе свойств `Блочная модель`?

### ISSUE THREAD

**Issue by RinatMullayanov** [htmlacademy/stylelint-config-htmlacademy#132]
Здравствуйте.
Есть вопрос к https://codeguide.academy/html-css.html#css-order
Свойство `overflow` относится к группе свойств `Блочная модель`?
Если да, то каким по порядку оно должно быть среди других свойств в группе?

**Comment by nikolai-shabalin** [comment]
> Свойство overflow относится к группе свойств Блочная модель?

Да, скорее всего к этой группе

> Если да, то каким по порядку оно должно быть среди других свойств в группе?

Любым. Определяйте его местоположение самостоятельно. Тут только одна рекомендация может быть, чтобы в разных CSS-правилах `overflow` имел постоянное место, например сверху группы, или снизу группы свойств
