### ISSUE TITLE
Добавить поддержку stylelint 14 и новее

### ISSUE THREAD

**Issue by dreadwood** [htmlacademy/stylelint-config-htmlacademy#18]
Сейчас если использовать конфиг с stylelint 14 и новее можно наткнутся на ошибку свойства "function-calc-no-invalid", которое [было удалено](https://stylelint.io/migration-guide/to-14/#function-calc-no-invalid-rule).

Нужно обновить в зависимостях stylelint до 14 иначе линтинг падает.

<img width="701" alt="Снимок экрана 2021-12-17 в 15 32 53" src="https://user-images.githubusercontent.com/48598846/146545371-bc47105e-ad5a-4af2-8aa5-e750be9751aa.png">

**Comment by nikolai-shabalin** [comment]
Спасибо за ишью.
Процесс обновления уже начался, но это мажорное обновление поэтому затянется. 

Помимо прочего там изменилась работа с препроцессорными файлами.

**Comment by Saran010** [comment]
Почти год прошёл. Есть какие-то движения? Подскажите, пожалуйста, почему это мажорное изменение?

**Comment by nikolai-shabalin** [comment]
Осталось совсем немного. Уже и PR висит.

Мажорное оно для нас. Потому что изменилась работа с препроцессорами

**Comment by nikolai-shabalin** [comment]
Смог толкнуть важный PR. Думаю на этой неделе сделаю релиз для stylelint 14+

**Comment by Saran010** [comment]
@nikolai-shabalin спасибо!) уже хотел сам толкнуть PR, но увидел аж два) будем ждать ;)

**Comment by firefoxic** [comment]
Кажется [свершилось](https://github.com/htmlacademy/stylelint-config-htmlacademy/pull/23) 😃  
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by nikolai-shabalin** [comment]
На этой неделе ещё будут доработки. Пока рано радоваться =)

**Comment by Saran010** [comment]
@nikolai-shabalin спасибо, обновился 😌

**Comment by nikolai-shabalin** [comment]
Прилетело #25 . Догнали сталйлинт 14.11.0. Чуть позже ещё обновления прилетят. Эту задачу закрываю. Всем спасибо
