### ISSUE TITLE
Добавить исключение для @use в SASS

### ISSUE THREAD

**Issue by ghost** [htmlacademy/stylelint-config-htmlacademy#19]

**Comment by firefoxic** [comment]
Кажется тут надо сделать одно из двух:
1. Если это правило нужно для предотвращения случайных опечаток в at-правилах, то надо тогда перечислить вообще все существующие в CSS, Less и Sass кроме запрещённого `extends`.
2. Если выше описанной цели нет, то можно и вовсе удалить это правило из конфига (препроцессоры и оптимизаторы и так крашнутся от неизвестного at-правила).
