### ISSUE TITLE
не работает

### ISSUE THREAD

**Issue by Elijah-I** [htmlacademy/stylelint-config-htmlacademy#22]
![12](https://user-images.githubusercontent.com/102501487/173178974-7d39e46a-e8b6-489c-bfde-7fe1c4eb7f2a.jpg)

**Comment by firefoxic** [comment]
А сам stylelint установлен? Начиная с версии 1.0.0 плагин stylelint для vscode требует отдельной установки stylelint в проект (или глобально).

**Comment by nikolai-shabalin** [comment]
Закрою задачу, так как она полностью остановилсь. 
Приходите ещё если найдёте, тогда поправим
