### ISSUE TITLE
Разобраться с peerDependency

### ISSUE THREAD

**Issue by nikolai-shabalin** [htmlacademy/stylelint-config-htmlacademy#39]

**Comment by firefoxic** [comment]
Из всего, что нашёл, какжется самое понятное объяснение от автора [`peerDependencies`](https://nodejs.org/es/blog/npm/peer-dependencies).

Как я понял:
1. Это важно авторам пакетов, которые не имеют в зависимостях (прямым указанием) хост-пакет, но опираются на его работу, основаны на нём. То есть классические плагины.
2. В нашем случае _stylelint_ — это хост-пакет.
3. Плагины к _stylelint_ (включая мой _stylelint-codeguide_) — это явный пример плагина, который может для тестов в дев-зависимостях и использовать хост-пакет (_stylelint_), но для прода в коде не используется. Наоборот, stylelint использует плагин в своей работе (к примеру, при попытке использовать мой плагин полностью на esm я получил ошибку, что cjs не может рекваирить esm — cjs в данном случае _stylelint_, именно он вызывает плагин, чтобы отработать какие-то кастомные фичи).
4. Относятся ли конфиги к таким плагинам? Технически вроде нет, это не плагины, а всего лишь объект с данными для настройки (он не запускается стайллинтом, что косвенно доказывает работоспособность моего esm-пакета конфига с cjs-стайллинтом). Но по факту в конфигах есть правила, которых не было в прошлой мажорке _stylelint_ или не будет в следующей, или наборы опций для правил могут оличаться и тд. Наша ситуация с 14→15→16 версиями в общем-то доказывает, что конфиги в контексте `peerDependencies` вполне проходят как «плагины». Ведь конфиг приходится серьёзно изменять, чтобы он продолжил работать в 16й и не ворчал в 15й версиях _stylelint_.
5. На всякий случай лучше и в конфиге (вернее в пакете) указать, с какими мажорками этот пакет точно работает. Пока лучше прописать `"~15.7.0"`. И лучше не `"15.x"`, потому что какие-то правила добавились в минорки позднее 15.0.0.
6. При обновлении _stylelint_ в зависимостях на 16+, надо будет протестировать работу конфига с этой новой мажоркой, и только тогда обновить мажорку в `peerDependencies`. А когда в минорку стайллинта добавляют новое правило и мы его добавляем в конфиг, нужно обновить минорку `peerDependencies` (продолжая использовать тильду). Это будет гарантировать, что вместе с новым конфигом случайно не поставят более старый _stylelint_ и не получится ошибка от него, что он не знает такого правила. За удалением правил ещё важнее следить.

Надеюсь ничего не перемудрил 🤓

**Comment by firefoxic** [comment]
Добавлю _stylelint_ в `peerDependencies` в #38

**Comment by nikolai-shabalin** [comment]
Спасибо. И отдельно за https://nodejs.org/es/blog/npm/peer-dependencies
