### ISSUE TITLE
Where is sort order?

### ISSUE THREAD

**Issue by seriiserii825** [htmlacademy/stylelint-config-htmlacademy#4]
Hi, i can understand, where is sort order rules?
Can you help me to understand?
Thanks.

**Comment by juwain** [comment]
Hello!

There is no sort order functionality in this config by default. But you can connect [stylelint-order](https://github.com/hudochenkov/stylelint-order) plugin to config to add such ability.

**Comment by seriiserii825** [comment]
Спасибо, я уже все сделал. 
Поздновато ответили, но, главное, что вопрос решил.

**Comment by efiand** [comment]
У Академии есть [порядок свойств](https://github.com/htmlacademy/codeguide/blob/master/.postcss-sorting.json), но плагина нет, как-то давно запилил свой, студенты иногда используют: https://www.npmjs.com/package/stylelint-order-htmlacademy

**Comment by nikolai-shabalin** [comment]
> Поэтому как-то давно запилил свой, студенты иногда используют: https://www.npmjs.com/package/stylelint-order-htmlacademy

А мы вроде его используем. Я перепроверю и внедрю в программу
