### ISSUE TITLE
Проверять установку значений кастомных свойств

### ISSUE THREAD

**Issue by balesniy** [htmlacademy/stylelint-config-htmlacademy#46]
внедрить правило [no-unknown-custom-properties](https://stylelint.io/user-guide/rules/no-unknown-custom-properties/)

мотивация - опечатки в этом случае сложно отлаживать, а мы хотим показывать кастомки новичкам.

возможные проблемы - правило работает только с одним источником, а на HTML2 студент может захотеть вынести значения в отдельный файл. стоит ли делать разный конфиг для разных курсов?

**Comment by firefoxic** [comment]
Думаю для препроцессоров можно тоже оставить — пусть резервные значения прописывают и тренируют полезный навык обеспечения надёжности компонента.
