### ISSUE TITLE
запретить camelCase в селекторах

### ISSUE THREAD

**Issue by balesniy** [htmlacademy/stylelint-config-htmlacademy#48]
включить правило https://stylelint.io/user-guide/rules/selector-class-pattern/

все остальное у нас в lower-case и только классы остались, которые мы просим называть в нижнем регистре в html

**Comment by firefoxic** [comment]
> все остальное у нас в lower-case

Не всё. Ещё бы вот это выкинуть:
https://github.com/htmlacademy/stylelint-config-htmlacademy/blob/efa35042230c26bebffce7e6b6eb389dcf48a773/.stylelintrc#L161-L163

**Comment by nikolai-shabalin** [comment]
Это таска про свойства.

Создал отдельную для [SVG-значений](https://github.com/htmlacademy/stylelint-config-htmlacademy/issues/130)
