### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ellq** [htmlacademy/stylelint-config-htmlacademy#7]
При использовании выпадает в ошибку 

> npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cat-energy-19@17.0.0 stylelint: `stylelint "source/sass/**/*.scss" --syntax scss`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the cat-energy-19@17.0.0 stylelint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

>npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lastq\AppData\Roaming\npm-cache\_logs\2020-05-13T13_35_51_369Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cat-energy-19@17.0.0 test: `npm run editorconfig && npm run stylelint`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the cat-energy-19@17.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

>npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lastq\AppData\Roaming\npm-cache\_logs\2020-05-13T13_35_51_396Z-debug.log

.stylelintrc:
`{`
`  "extends": "stylelint-config-htmlacademy",`
`  "rules": {`
`    "declaration-no-important": true,`
`    "indentation": [2, {"ignore": ["inside-parens"]}]`
`  }`
`}`

**Comment by nikolai-shabalin** [comment]
Слишком мало данных. Не понять, что за ошибка. Сможете вспомнить проект?

**Comment by nikolai-shabalin** [comment]
Закрываю. Мне не хватило данных.
